### ISSUE TITLE
Support: what is the best way to handle en/dis of modules?

### ISSUE THREAD

**Issue by denics** [Happyculture/combawa#31]
postdeploy_actions is great. One of the actions that I usually do is to enable / disable modules (i.e. dis devel in dev and recette, en googleanalytics in prod). Also the modules to en/dis vary among environments.
As this happen ALWAYS, I was thinking about declare arrays in .env that will be en/dis by postdeploy like:

```bash
for LINE in "${COMBAWA_RECETTE_DIS}"
do
  $DRUSH dis -y $LINE
done 
for LINE in "${COMBAWA_RECETTE_EN}"
do
  $DRUSH en -y $LINE
done
etc.
```

**Comment by Artusamak** [comment]
Since you can tweak you .env files as you want and customize the postdeploy script you can perfectly do it if you prefer this behavior, yes.

This is a grey zone to decide if this should be defined in the .env or in the postdeploy script. But the good news is that it's up to you. I'd personally vote for postdeploy script for two reasons:
1/ This variable may not be used elsewhere so why bringing it to the .env? We usually put sensitive data there that should not be versioned.
2/ Each project will have its own set of modules and the disable step is within the logic of the postdeploy script. Its not comfortable to figure out which modules are disabled on prod if you don't connect on the environment itself. Plus that may be a strong choice to avoid to have the whole team accessing the prod server. If the team really wanted to have this module list changed, they would have to open a ticket with the devops team just to change a variable. That's not really a frictionless process to deploy changes.
